// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


/**
 * Service wraps a bound type instance.
 * The zero value of Service is invalid.
 * Valid values may only be obtained by calling [NewService].
 */
export interface Service {
}
