// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * @returns {Promise<model$0.VrchatModel> & { cancel(): void }}
 */
export function GetModel() {
    let $resultPromise = /** @type {any} */($Call.ByID(3276440787));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Name() {
    let $resultPromise = /** @type {any} */($Call.ByID(476499185));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = model$0.VrchatModel.createFrom;
