// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class VrchatModel {
    /**
     * Creates a new VrchatModel instance.
     * @param {Partial<VrchatModel>} [$$source = {}] - The source object to create the VrchatModel.
     */
    constructor($$source = {}) {
        if (!("IsRunning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsRunning"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VrchatModel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VrchatModel}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VrchatModel(/** @type {Partial<VrchatModel>} */($$parsedSource));
    }
}
