// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$1 from "../../vrchat/model/models.js";

export interface Model {
    "Vrchat": model$1.VrchatModel;
    "Osc": model$0.OscModel;
    "Steamvr": model$0.SteamvrModel;
}
