// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


export interface OscModel {
    "ServerIsRunning": boolean;
    "ClientIsRunning": boolean;
}

export interface SteamvrModel {
    "IsRunning": boolean;
}
