// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function OnShutdown() {
    let $resultPromise = /** @type {any} */($Call.ByID(2081876197));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function OnStartup() {
    let $resultPromise = /** @type {any} */($Call.ByID(4152630384));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Quit() {
    let $resultPromise = /** @type {any} */($Call.ByID(2886621773));
    return $resultPromise;
}
