// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function GetModel(): Promise<model$0.VrchatModel> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1613575085) as any;
    return $resultPromise;
}

export function Quit(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(928129283) as any;
    return $resultPromise;
}
